version: "3.9"
services:
 flask_app:
   container_name: flask_app
   image: masdija1145/diad:1.0
   build: .
   ports:
     - "3000:3000"
   environment:
     - DB_URL=postgresql+psycopg2://postgres:123@diadb:5432/postgres


   depends_on:
   - diadb

 diadb:
   container_name: flask_db
   image: postgres:12
   ports:
     - "5432:5432"
   environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
   volumes:
     - pgdata:/var/lib/postgresql/data

volumes:
 pgdata: {}